database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "zero2prod"
email_client:
  base_url: "smtp.163.com"
  sender_email: "17610780919@163.com"
  token: QMveC3B6DD8zuJJN
application:
  host: "0.0.0.0"
  port: 8080
  base_url: "/zero2prod"
